### ISSUE TITLE
Final newline

### ISSUE THREAD

**Issue by ImmernochPeter** [Steppenstreuner/mybb-discordbot#15]
Maybe its just a github bug but it looks like your file has no final newline...

Check your settings.json for the following lines:

```json
"files.insertFinalNewline": true,
 "files.trimTrailingWhitespace": true,
```

the will delete every trailing white spaces and add a final newline to your files if there is no one

**Comment by Steppenstreuner** [comment]
It's a discord thing, pylint would explode without FNL 
but thanks for your settings.json entries
